# Generated by Django 2.0.7 on 2018-08-02 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_time']},
        ),
    ]
