# Generated by Django 2.0.7 on 2018-08-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180803_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ['-priority']},
        ),
    ]
